name: Auto Update README

on:
  workflow_dispatch:  # memungkinkan manual run
  schedule:
    - cron: '0 7 * * *'   # 13:57 WIB
    - cron: '0 9 * * *'    # 16:00 WIB
    - cron: '5 9 * * *'    # 16:05 WIB
    - cron: '10 9 * * *'   # 16:10 WIB
    - cron: '15 9 * * *'   # 16:15 WIB
    - cron: '20 9 * * *'   # 16:20 WIB

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README
        run: |
          echo "Update: $(date '+%Y-%m-%d %H:%M:%S')" >> README.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto update README $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push