name: Auto Update README

on:
  workflow_dispatch:
  schedule:
    - cron: '57 6 * * *'   # 13:57 WIB
    - cron: '0 9 * * *'    # 16:00 WIB
    - cron: '5 9 * * *'    # 16:05 WIB
    - cron: '10 9 * * *'   # 16:10 WIB

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update README File
        run: |
          TIME=$(date -u '+%Y-%m-%d %H:%M:%S')
          WIB_TIME=$(date -d "$TIME +7 hours" '+%Y-%m-%d %H:%M:%S')
          CONTENT="> 🕒 **Last Update:** $WIB_TIME WIB"

          # pastikan marker ada
          if ! grep -q "<!-- START -->" README.md; then
            echo "<!-- START -->" >> README.md
            echo "<!-- END -->" >> README.md
          fi

          # replace isi antara marker
          awk -v content="$CONTENT" '
          /<!-- START -->/ {print; print content; skip=1; next}
          /<!-- END -->/ {skip=0}
          !skip
          ' README.md > temp.md && mv temp.md README.md

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto update README $WIB_TIME" || echo "No changes to commit"
          git push